epochs: 25
parameters:
  batch_size: 32
  bit_depth: 8
  dropout: 0.5
  epochs: 25
  image_size: 224
  learningrate: 0.001
  learningrate_sheduler: CosineAnnealingWarmRestarts
  model: efficientnet_b4
  normalization: imagenet
  num_channels: 3
  num_classes: 5
  optimizer: adam
  pretrained: false #true for pretraining & false for transfer learning
  progressbar: false
  save_inference_images: true
  seed: 42
  test_time_augmentation: true
  test_time_dropout: true
  test_time_iterations: 10
  transfer: true # false for pretraining & true for transfer learning
  verbose: 0
paths:
  data_path: /.../UncertaintyAwareSlumMapping/data/transfer/images
  log_path: /.../UncertaintyAwareSlumMapping/data/transfer
  pretrain_base_dir: /.../UncertaintyAwareSlumMapping/data/pretrain/logs